import json
import os
import csv
import time
from google import genai
from dotenv import load_dotenv
from utils import VerificationResult, VIOLATION_TYPES, log_event, SYSTEM_PROMPT

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

# --- Auditor Prompt ---
AUDITOR_SYSTEM_PROMPT = f"""
You are a strict Auditor for an AI generating flashcards.
Your job is not to generate flashcards, but to audit the flashcards generated by that AI for quality and adherence to guidelines. You will be given the headword and the AI's response (which includes the flashcard data). You must analyze the response and determine if it meets the quality standards.

## Guidelines for auditing
Here's the system prompt given to that AI.
```
{SYSTEM_PROMPT}
```

## Violation types
{json.dumps(VIOLATION_TYPES, indent=2, ensure_ascii=False)}
"""

def verify_card(headword, response_json, human_examples):
    # Construct the few-shot context from human examples
    few_shot_context = ""
    if human_examples:
        few_shot_context = "### GOLD STANDARD EXAMPLES (PERFECT CARDS):\n"
        for ex in human_examples:
            few_shot_context += f"Word: {ex['headword']}\nJSON: {json.dumps(ex['response'], ensure_ascii=False)}\n---\n"

    prompt = f"{few_shot_context}\n\nAudit the following flashcard data for the word '{headword}':\n\n{response_json}"
    
    try:
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite-preview",
            contents=prompt,
            config={
                "system_instruction": AUDITOR_SYSTEM_PROMPT,
                "response_mime_type": "application/json",
                "response_schema": VerificationResult,
                "temperature": 0.01,
            }
        )
        return response.parsed
    except Exception as e:
        print(f"    API Error verifying {headword}: {e}")
        return None

def main():
    # 1. Load Level
    try:
        with open("config.json", "r") as f:
            config = json.load(f)
            level = config.get("level", 3)
    except:
        level = 3

    # 2. Fetch Human Examples for 10-shot prompting
    from utils import get_random_human_examples
    human_examples = get_random_human_examples(level, 10)
    print(f"Loaded {len(human_examples)} human-verified examples for few-shot audit.")

    file_path = f"data/raw/level{level}.tsv"
    if not os.path.exists(file_path):
        print(f"File {file_path} not found.")
        return

    # 3. Read all rows
    rows = []
    with open(file_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        fieldnames = reader.fieldnames
        rows = list(reader)

    # 4. Process 'none' state cards
    pending = [r for r in rows if r.get("verification") == "none"]
    print(f"Verifying {len(pending)} cards for Level {level}...")

    updated_count = 0
    for row in pending:
        headword = row["headword"]
        print(f"  Auditing: {headword}...")
        
        result = verify_card(headword, row["response"], human_examples)
        if result:
            old_state = row["verification"]
            row["verification"] = "ai_pass" if result.status == "pass" else "ai_fail"
            row["violations"] = json.dumps(result.violations)
            row["comment"] = result.comment
            
            # Log the event
            log_event(level, headword, "verifier", old_state, row["verification"], row["response"], result.violations)
            updated_count += 1
            time.sleep(1) # Be polite

    # 4. Save updates back to TSV
    if updated_count > 0:
        with open(file_path, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
            writer.writeheader()
            writer.writerows(rows)
        print(f"Done! Updated {updated_count} cards.")
    else:
        print("No cards needed verification.")

if __name__ == "__main__":
    main()
