import json
import os
import csv
import time
from typing import List, Optional, Dict, Any
from google import genai
from dotenv import load_dotenv
from utils import BatchVerificationResult, VerificationResult, get_random_human_examples, SYSTEM_PROMPT

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

# --- Auditor Prompt ---
AUDITOR_SYSTEM_PROMPT = f"""
You are a VERY STRICT and SKEPTICAL GSAT English teacher auditing vocabulary flashcards. 
Your primary goal is to find errors. You are a "Critic AI" - your default assumption is that the card has quality issues. For each of the cards, return one entry. Write nothing in the comments if PASS.

### FAILURE CHECKLIST (FAIL if any are true):
- TAG_SCOPE_ERROR: Tagged a simple noun/object or common article.
- INCOMPLETE_PATTERN: Missing the key preposition or particle that makes the phrase a "collocation".
- DENSITY_ERROR: Versatile words (like 'account', 'leave', 'strike') have fewer than 4 example sentences.
- STYLE_MISMATCH: Sentences are too short or doesn't demonstrate the usage correctly, or in any way that doesn't match the given standard examples.
- MISSING_EXPLANATION: The explanation in any field is inadequate.
- VIOLATION OF SYSTEM PROMPT: The flashcard generated by the AI doesn't follow the system prompt instructions.

### ORIGINAL SYSTEM PROMPT (The "Creator's" Instructions):
{SYSTEM_PROMPT}


For each card in the batch, you MUST be critical. If a collocation is just a common adjective-noun pair, FAIL it. We only want high-value patterns.
"""

def verify_batch(batch_items: List[Dict[str, str]], human_examples: List[Dict[str, Any]]) -> Optional[BatchVerificationResult]:
    few_shot = "### GOLD STANDARD EXAMPLES (PERFECT):\n"
    for ex in human_examples:
        few_shot += f"Word: {ex['headword']}\nJSON: {json.dumps(ex['response'], ensure_ascii=False)}\n---\n"

    batch_prompt = f"{few_shot}\n\n### BATCH TO AUDIT (Be very critical):\n"
    for i, item in enumerate(batch_items):
        batch_prompt += f"Card {i+1} ({item['headword']}):\n{item['response']}\n---\n"
    
    try:
        response = client.models.generate_content(
            model="gemma-4-31b-it",
            contents=batch_prompt,
            config={
                "system_instruction": AUDITOR_SYSTEM_PROMPT,
                "response_mime_type": "application/json",
                "response_schema": BatchVerificationResult,
                "temperature": 0.1,
            }
        )
        return response.parsed
    except Exception as e:
        print(f"Error verifying batch: {e}")
        return None

def main() -> None:
    # Load level from config
    verify_level = 3

    human_examples = get_random_human_examples(verify_level, 10)
    file_path: str = f"data/raw/level{verify_level}.tsv"
    
    if not os.path.exists(file_path):
        print(f"File {file_path} not found.")
        return

    # Read all rows
    rows: List[Dict[str, str]] = []
    with open(file_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        fieldnames: Optional[List[str]] = reader.fieldnames
        rows = list(reader)

    if not fieldnames: return

    # Identify cards needing verification
    pending_indices = [i for i, r in enumerate(rows) if r.get("verification") == "none"]
    print(f"Auditing {len(pending_indices)} cards in batches of 50 for Level {verify_level}...")

    updated_count = 0
    batch_size = 20
    
    for i in range(0, len(pending_indices), batch_size):
        batch_idx_chunk = pending_indices[i : i + batch_size]
        batch_items = [rows[idx] for idx in batch_idx_chunk]
        
        print(f"  Processing batch {i//batch_size + 1} ({len(batch_items)} cards)...")
        
        batch_result = verify_batch(batch_items, human_examples)
        
        if batch_result and len(batch_result.results) == len(batch_items):
            for result, row_idx in zip(batch_result.results, batch_idx_chunk):
                rows[row_idx]["verification"] = "ai_pass" if result.status == "pass" else "ai_fail"
                rows[row_idx]["comment"] = result.comment
                updated_count += 1
            print(f"    Batch complete. Total updated: {updated_count}")
        else:
            print(f"    Error: Batch size mismatch or API failure. Skipping batch.")
        
        time.sleep(2) # Be polite to API

    # Save updates back to TSV
    if updated_count > 0:
        with open(file_path, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
            writer.writeheader()
            writer.writerows(rows)
        print(f"Successfully verified {updated_count} cards.")
    else:
        print("No cards needed verification.")

if __name__ == "__main__":
    main()
