import json
import os
import csv
import time
import asyncio
import random
import argparse
from typing import List, Optional, Dict, Any, Tuple
from google import genai
from google.genai import types
from dotenv import load_dotenv
from utils import BatchVerificationResult, VerificationResult, get_few_shots, SYSTEM_PROMPT, get_common_parser, Flashcard, BatchFlashcard

load_dotenv()
client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY"), 
    http_options={
        "timeout": 180_000 # 2 minute
    }
)

# --- Auditor Prompt ---
AUDITOR_SYSTEM_PROMPT = f"""
You are a VERY STRICT and SKEPTICAL GSAT English teacher auditing vocabulary flashcards. 
Your primary goal is to find errors. You are a "Critic AI" - your default assumption is that the card has quality issues, the cards are made by a student and is full of errors. Even the tiniest error is worth correcting for the good of the student on a test. 

### YOUR TASK:
For each card in the batch:
1. Repeat the **headword**.
2. Determine the **status** ("pass" or "fail").
3. Return one entry for **HOW TO FIX THE ISSUE** (e.g. Delete <pattern> ... </pattern> tags from sentence 1, do not remove the content inside; Add another sentence at the end using the collocation X). Write nothing in the comments if PASS. Be aware that there's often far more than a single issue per card, please list them ALL. You MUST be critical and strict.

### FAILURE CHECKLIST (FAIL if any are true):
- VIOLATION_OF_SYSTEM_PROMPT: The flashcard generated by the AI doesn't follow the system prompt instructions.
- PART_OF_SPEECH_MISMATCH: The part of speech in the sentence does not match the part of speech in the pattern.
- INVERTED_TAGS: The pattern and target tags are inverted.
- INCOMPLETE_PATTERN: The pattern is not fully tagged with `<pattern> ... </pattern>`.
- DENSITY_ERROR: Versatile words (like 'account', 'leave', 'strike', 'cast') have fewer than 3-4 listed patterns.
- MISSING_EXAMPLES: Critical collocations or patterns are not covered.
- PATTERN_WITH_INSUFFICIENT_EXAMPLES: A pattern is missing examples. Sometimes multiple sentences are needed.
- STYLE_MISMATCH: Sentences are too short or doesn't demonstrate the usage correctly (it should be able to be infered without knowing the word), or in any way that doesn't match the given standard examples.
- INSUFFICIENT_EXPLANATION: The explanation in any field is inadequate.
- DIFFICULTY_MISMATCH: The sentence is too difficult/easy for the headword.
- MISSING_COLLOCATIONS: Does not include important usage patterns.
- AWKWARD_TRANSLATION: The Tradition Chinese translation is unnatural.
- SENTENCE_TOO_SHORT: The sentence is too short.
- CANNOT_INFER: Cannot infer the meaning of the headword from the given example sentence. (e.g. "He was very lachrymose yesterday." Here, there's no way to infer the meaning of "lachrymose" from the sentence.)
- UNEXEMPLIFIED_EXPLANATION: The explanation mentioned something important but there are no corresponding examples.
- CONTAINS_GIBBERISH: Any of the sentences, explanations or translations contains gibberish characters or any other weird characters from other languages.
- CONTAINS_TYPO: Any of the sentences, explanations or translations contains typos.
- GRAMMARICAL_ERROR: The grammar of the sentence is incorrect.
- ILLOGICAL_SENTENCE: The sentence is illogical culturally or semantically.
- LEAKED_INSTRUCTIONS: The explanation contains information about the prompt, instead of the content for the flashcard.
- FIELD_MISMATCH: The fields contains information that belongs in another field.
- OTHER_ISSUE: Other weird issues not already mentioned.

### ORIGINAL SYSTEM PROMPT (The "Creator's" Instructions, see if its work matches the system prompt. If not, FAIL):
{SYSTEM_PROMPT}
"""

async def verify_batch_async(batch_items: List[Dict[str, str]], human_examples: List[Tuple[str, Flashcard]]) -> Optional[BatchVerificationResult]:
    few_shot = "### GOLD STANDARD EXAMPLES (PERFECT):\n"
    for ex in human_examples:
        (headword, flashcard) = ex
        few_shot += f"Word: {headword}\nJSON: {flashcard.model_dump_json()}\n---\n"

    batch_prompt = f"{few_shot}\n\n### BATCH TO AUDIT (Be very critical):\n"
    for i, item in enumerate(batch_items):
        batch_prompt += f"Card {i+1} ({item['headword']}):\n{item['response']}\n---\n"
    
    try:
        # Utilize the non-blocking asynchronous SDK endpoint .aio
        response = await client.aio.models.generate_content(
            model="gemma-4-31b-it",
            contents=batch_prompt,
            config=types.GenerateContentConfig(
                system_instruction=AUDITOR_SYSTEM_PROMPT,
                response_mime_type="application/json",
                response_schema=BatchVerificationResult,
                temperature=0.3,
                thinking_config=types.ThinkingConfig(
                    include_thoughts=False,
                    thinking_level="high" # type: ignore
                )
            )
        )
        return response.parsed # type: ignore
    except Exception as e:
        print(f"Error verifying batch: {e}")
        return None

def write_entire_tsv(file_path: str, fieldnames: List[str], rows: List[Dict[str, str]]) -> None:
    """Helper used to safely execute blocking disk serialization inside an OS threadpool."""
    with open(file_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)

async def audit_chunk_slot(
    semaphore: asyncio.Semaphore,
    file_path: str,
    fieldnames: List[str],
    rows: List[Dict[str, str]],
    batch_idx_chunk: List[int],
    human_examples: List[Tuple[str, Flashcard]],
    file_lock: asyncio.Lock,
    batch_num: int,
    total_batches: int,
    counter_dict: Dict[str, int]
):
    """Executes a batch audit using a strict semaphore-controlled async slot wrapper."""
    async with semaphore:
        # Random jitter to avoid thundering herd when slots open up
        await asyncio.sleep(random.uniform(0, 3))
        batch_items = [rows[idx] for idx in batch_idx_chunk]
        timestamp = time.strftime("%H:%M:%S")
        print(f"[{timestamp}] Processing batch {batch_num} of {total_batches}...")
        start_time = time.perf_counter()
        
        success = False
        attempts = 0
        while not success:
            try:
                # API context processing handles out-of-order execution outside the file lock
                batch_result = await verify_batch_async(batch_items, human_examples)
                
                if not batch_result or len(batch_result.results) != len(batch_items):
                    if batch_result:
                        raise ValueError(f"Batch size mismatch (required {len(batch_items)}, got {len(batch_result.results)}).")
                    else:
                        raise ValueError("API returned an empty payload or malformed validation block.")

                # Mutate state and commit serialization atomically inside the lock
                async with file_lock:
                    for result, row_idx in zip(batch_result.results, batch_idx_chunk):
                        rows[row_idx]["verification"] = "ai_pass" if result.status == "pass" else "ai_fail"
                        rows[row_idx]["comment"] = result.comment
                        counter_dict["updated_count"] += 1
                    
                    await asyncio.to_thread(write_entire_tsv, file_path, fieldnames, rows)
                    elapsed = time.perf_counter() - start_time
                    timestamp = time.strftime("%H:%M:%S")
                    print(f"[{timestamp}] Successfully processed batch {batch_num} in {elapsed:.2f}s.")

                success = True
                
            except Exception as e:
                attempts += 1
                if attempts >= 3:
                    print(f"    Max attempts reached for batch {batch_num}. Skipping data slice.")
                    break
                print(f"    Error at batch {batch_num} (attempt {attempts}): {e}")
                await asyncio.sleep(12)  # Cooldown padding block to alleviate gateway density

async def main_async() -> None:
    # Configurations
    parser = get_common_parser("Level to audit.")
    parser.add_argument("--batch-size", "-b", type=int, default=5, help="Batch size for processing.")
    parser.add_argument("--worker-count", "-w", type=int, default=5, help="Number of concurrent workers.")
    args = parser.parse_args()
    
    verify_level = args.level
    batch_size = args.batch_size
    workers = args.worker_count

    human_examples = get_few_shots()
    file_path: str = f"data/raw/level{verify_level}.tsv"
    
    if not os.path.exists(file_path):
        print(f"File {file_path} not found.")
        return

    # Read all rows into initial memory array
    with open(file_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        if not reader.fieldnames:
            raise Exception("No fieldnames found in TSV file.")
        fieldnames: List[str] = list(reader.fieldnames)
        rows = list(reader)

    if not fieldnames: 
        return

    # Identify cards needing verification
    pending_indices = [i for i, r in enumerate(rows) if r.get("verification") == "none"]
    total_pending = len(pending_indices)

    if total_pending == 0:
        print("No cards needed verification.")
        return
        
    print(f"Auditing {total_pending} cards in batches of {batch_size} for Level {verify_level}...")
    
    # Initialize shared variables and primitives
    counter_dict = {"updated_count": 0}
    file_lock = asyncio.Lock()
    pool_semaphore = asyncio.Semaphore(workers)
    
    batches_indices = [pending_indices[i : i + batch_size] for i in range(0, total_pending, batch_size)]
    total_batches = len(batches_indices)

    tasks = []
    for idx, batch_idx_chunk in enumerate(batches_indices):
        task = audit_chunk_slot(
            semaphore=pool_semaphore,
            file_path=file_path,
            fieldnames=fieldnames,
            rows=rows,
            batch_idx_chunk=batch_idx_chunk,
            human_examples=human_examples,
            file_lock=file_lock,
            batch_num=idx + 1,
            total_batches=total_batches,
            counter_dict=counter_dict
        )
        tasks.append(task)

    # Resolve all pipeline steps matching pool context allocations
    await asyncio.gather(*tasks)

    updated_count = counter_dict["updated_count"]
    if updated_count > 0:
        print(f"Verification session finished. Successfully verified {updated_count} cards. {total_pending - updated_count} remaining.")

if __name__ == "__main__":
    asyncio.run(main_async())
